### ISSUE TITLE
Stake Pool Node Crashing 

### ISSUE THREAD

**Issue by BitcoinMicroPaymentNetwork** [cardano-foundation/incentivized-testnet-stakepool-registry#1065]
Dec 24 20:51:28.253 ERRO Error while accepting connection on 0.0.0.0:3000: Os { code: 24, kind: Other, message: "Too many open files" }, task: network
Dec 24 20:51:28.255 INFO service finished with error, task: network
Dec 24 20:51:28.255 CRIT Service has terminated with an error

**Comment by KtorZ** [comment]
For any issue with Jörmungandr or jcli, please refer to the official repository: https://github.com/input-output-hk/jormungandr/issues?q=is%3Aissue+too+many+open+files+is%3Aclosed

Cheers.
