### ISSUE TITLE
Keep creating orphan Blocks...

### ISSUE THREAD

**Issue by glagolef** [cardano-foundation/incentivized-testnet-stakepool-registry#1075]
Issue: Since moving to 8.5, I've created 4/6 orphan blocks due to blocks which did not make it into the blockchain. I then moved back to 8.4 using same config and orphaned 1 more block. I don't understand what's going on.

Examples:
2019-12-24T17:20:10.758775250+00:00"
  enclave_leader_id: 1
  finished_at_time: "2019-12-24T17:26:29.018736771+00:00"
  scheduled_at_date: "10.39986"
  scheduled_at_time: "2019-12-24T17:26:29+00:00"
  status:
    Block:
      block: 9aad032a67592861e765e0f764907a844d79fa74c3d067f344544e4e4d096365
      chain_length: 36732
  wake_at_time: "2019-12-24T17:26:29.001905758+00:00"

created_at_time: "2019-12-24T03:34:21.423650054+00:00"
  enclave_leader_id: 1
  finished_at_time: "2019-12-24T03:41:21.017944194+00:00"
  scheduled_at_date: "10.15232"
  scheduled_at_time: "2019-12-24T03:41:21+00:00"
  status:
    Block:
      block: 9202faafb863ba1437c1433a3163c1f8216f46d145978a0514825236d07a6031
      chain_length: 35006
  wake_at_time: "2019-12-24T03:41:21.001702587+00:00"

This one happened when I switched back to v0.8.4
- created_at_time: "2019-12-24T18:27:38.627432484+00:00"
  enclave_leader_id: 1
  finished_at_time: "2019-12-24T18:41:43.016877296+00:00"
  scheduled_at_date: "10.42243"
  scheduled_at_time: "2019-12-24T18:41:43+00:00"
  status:
    Block:
      block: 8af8abc91f17ade8b40f5b1b2e1a0177d05484bc39efc11cac6ac557ceff3ba9
      chain_length: 36900
  wake_at_time: "2019-12-24T18:41:43.001534605+00:00"

Here's my config:
{
  "log": [
    {
      "format": "plain",
      "level": "info",
      "output": "stderr"
    }
  ],
  "storage": "./storage/",
  "p2p": {    
    "listen_address": "/ip4/0.0.0.0/tcp/59256",
    "public_address": "/ip4/107.152.35.85/tcp/59256",
    "public_id": "2b7de67fdb977089bb315cb812f3332db44562a45a0a54be",
    "topics_of_interest": {
      "blocks": "high",
      "messages": "high"
    },
    "max_connections": 512,
    "max_unreachable_nodes_to_connect_per_event": 15,
    
    "trusted_peers": [
    {
        "address": "/ip4/13.56.0.226/tcp/3000",
        "id": "7ddf203c86a012e8863ef19d96aabba23d2445c492d86267"
    },
    {
        "address": "/ip4/54.183.149.167/tcp/3000",
        "id": "df02383863ae5e14fea5d51a092585da34e689a73f704613"
    },
    {
        "address": "/ip4/52.9.77.197/tcp/3000",
        "id": "fcdf302895236d012635052725a0cdfc2e8ee394a1935b63"
    },
    {
        "address": "/ip4/18.177.78.96/tcp/3000",
        "id": "fc89bff08ec4e054b4f03106f5312834abdf2fcb444610e9"
    },
    {
        "address": "/ip4/18.182.115.51/tcp/3000",
        "id": "8529e334a39a5b6033b698be2040b1089d8f67e0102e2575"
    },
    {
        "address": "/ip4/18.184.35.137/tcp/3000",
        "id": "06aa98b0ab6589f464d08911717115ef354161f0dc727858"
    },
    {
        "address": "/ip4/3.125.31.84/tcp/3000",
        "id": "8f9ff09765684199b351d520defac463b1282a63d3cc99ca"
    },
    {
        "address": "/ip4/3.125.183.71/tcp/3000",
        "id": "9d15a9e2f1336c7acda8ced34e929f697dc24ea0910c3e67"
    },
    {
        "address": "/ip4/52.9.132.248/tcp/3000",
        "id": "671a9e7a5c739532668511bea823f0f5c5557c99b813456c"
    },
    {
        "address": "/ip4/52.8.15.52/tcp/3000",
        "id": "18bf81a75e5b15a49b843a66f61602e14d4261fb5595b5f5"
    },
    {
        "address": "/ip4/13.112.181.42/tcp/3000",
        "id": "52762c49a84699d43c96fdfe6de18079fb2512077d6aa5bc"
    },
    {
        "address": "/ip4/3.125.75.156/tcp/3000",
        "id": "22fb117f9f72f38b21bca5c0f069766c0d4327925d967791"
    },  
    {
        "address": "/ip4/3.124.116.145/tcp/3000",
        "id": "99cb10f53185fbef110472d45a36082905ee12df8a049b74"
    }
    ]
  },
  "rest": {
    "listen": "127.0.0.1:59649"
  },
  mempool:{
    "fragment_ttl": "2h",
    "log_ttl": "24h",
    "garbage_collection_interval": "2h"
  }
}

**Comment by glagolef** [comment]
I can provide logs if needed

**Comment by glagolef** [comment]
I think part of the issue for some reason was the port address I chose for Rest API. I changed it to the standard ones around 3000, and it seems to have fixed the issues I was having before.
Also 8.4 seems to be running much better, requiring less frequent restarts, at least in my case, than 8.5.

**Comment by KtorZ** [comment]
I get it that this was due to a misconfiguration and a node not connected to the network ?

**Comment by glagolef** [comment]
Likely. I've changed the node config and moved to a different server and 8.5 is running smoothly now.

**Comment by glagolef** [comment]
Thanks
