### ISSUE TITLE
Node Crash Error while accepting connection on 0.0.0.0:3000

### ISSUE THREAD

**Issue by BitcoinMicroPaymentNetwork** [cardano-foundation/incentivized-testnet-stakepool-registry#1080]
Dec 25 00:51:54.563 INFO connecting to peer, node_id: d91ef2ed737f4ada7c648265d16478414f1eaa6fd2108cff, peer_addr: 85.25.159.219:3000, task: network
Dec 25 00:51:54.572 ERRO Error while accepting connection on 0.0.0.0:3000: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, task: network
Dec 25 00:51:54.573 WARN response canceled by the processing task, request: UploadBlocks, sub_task: server, task: network
Dec 25 00:51:54.573 WARN response canceled by the processing task, request: UploadBlocks, sub_task: server, task: network
Dec 25 00:51:54.575 INFO service finished with error, task: network
Dec 25 00:51:54.576 CRIT Service has terminated with an error
A service has terminated with an error

**Comment by KtorZ** [comment]
I see you've already open a ticket on the official Jörmungandr's repository: https://github.com/input-output-hk/jormungandr/issues/1458. 

Closing this one.
