### ISSUE TITLE
Remove pool or wrong ticker from chain

### ISSUE THREAD

**Issue by W3S88** [cardano-foundation/incentivized-testnet-stakepool-registry#1153]
When registering the pool I have adjusted the fee several times... with the same ticker. it is possible to remove the 2 wrong tickers. Since there is only a physical pool and the other 2 doing nothing but are still visible.

**Comment by KtorZ** [comment]
Hey!

Please have a look at: https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/issues/768

Note that you don't need to re-create a pool to adjust the fee. You could instead use a management certificate to tweak out parameters. This is detailed in Jörmungandr/JCLI documentation.
