### ISSUE TITLE
Stakepool BKIND not being selected as leader

### ISSUE THREAD

**Issue by Gertjan-stakingpoolholder** [cardano-foundation/incentivized-testnet-stakepool-registry#1257]
Hi,

In the community I mentioned my stake-pool, ticker name BKIND, has not been selected yet as a leader. Based upon advice given by one of the community members, I would like to request the K=100 parameter to be changed to K=500 for my pool: BKIND. Can this be done?

With kind regards,
Gertjan

**Comment by KtorZ** [comment]
Hi. There are unfortunately many things called `k` in Ouroboros Praos... Which one are you referring to? 
Having said that, the only bits that are configurable for your pool are:

1. The tax parameters:
    - fixed: this is the fixed cut the stake pool will take from the total reward due to the stake pool;
    - ratio: this is the percentage of the remaining value that will be taken from the total due    
    - limit: a value that can be set to limit the pool's Tax.

2. The management threshold: This is the number of owners keys that are required to update the stake pools parameter (the tax, update the keys, the threshold itsef...).

3. Your credentials (VRF/KES keys, Owner key(s)) ...

The rest is determined by the protocol itself but, once the update system is introduced, pool leaders will be able to influence those protocol parameters through voting. 

Now, one important thing to keep in mind is that the leader election is a random process that depends on your total stake. The more you own, the more likely you are to be elected. Perhaps your pool is simply not "big enough".

**Comment by Gertjan-stakingpoolholder** [comment]
Thanks for the information. The K for defining the number of Stakepools.

**Comment by KtorZ** [comment]
The saturation threshold would be "updatable" via on-chain updates on the MainNet, for the incentivized TestNet however, updates won't likely be available.
