### ISSUE TITLE
ERRO cannot schedule pulling headers

### ISSUE THREAD

**Issue by Gertjan-stakingpoolholder** [cardano-foundation/incentivized-testnet-stakepool-registry#1397]
The following console messages like below appear frequently:

Jan 04 16:50:10.383 ERRO cannot schedule pulling headers, reason: failed to send a command: channel closed, from_node_id: a74ecf0adc8955e44fb5266c69eec7fb3ccb3a8a4a57535e, date: 21.36969, parent: e7cb5ab79c962f2c3172860ecaec4f4851edac1c1b082340a0b53b5f4c75ba38, hash: aa53bea89d257e3e184e655485bf0f1ceb124c93374b7377c447d6d9fba3b050, task: block

Running on 0.8.5 (stakcepool) with the trusted peers for ITN Rewards.

**Comment by KtorZ** [comment]
Hey! For any trouble with `jormungandr` or `jcli`, please refer to the official repository: https://github.com/input-output-hk/jormungandr/issues

Make sure to lookup possible existing issues before opening a new one!
