### ISSUE TITLE
Unable to check balance of the address.

### ISSUE THREAD

**Issue by anthlic** [cardano-foundation/incentivized-testnet-stakepool-registry#1421]
I am creating a stake pool and am having the following error when i try to check the balance of my stake pool account.
failed to make request.
failed to make a REST request
  |-> node rejected request because of invalid parameters
  |-> http://127.0.0.1:3100/api/v0/account/4b213361b6ca1b653fb96289ebcfd31c5e61c245d9db95826063a42edf6492f3: Client Error: 404 Not Found

The command i am executing is.
ADD=addr1s49jzvmpkm9pkeflh93gn6706vw9ucwzghvah9vzvp36gtklvjf0xjzgcnp
jcli rest v0 account get $ADD -h http://127.0.0.1:3100/api

**Comment by anthlic** [comment]
In Explorer i can see there are 10 ADA that i had transferred from my Incentivized Testnet Daedalus wallet.

**Comment by sdalmeida** [comment]
@anthlic I just checked your wallet address on my server and it looks like its fine
![image](https://user-images.githubusercontent.com/1103528/72033952-ba7a1180-3261-11ea-9e9e-3aa965814d05.png)

I have ran into the same issue as you in the past. Your node needs to be synced or else you will get a 404 like above. If you're still having this issue, restart your node. 

You can always check your address balance here too: https://shelleyexplorer.cardano.org/en/address/addr1s49jzvmpkm9pkeflh93gn6706vw9ucwzghvah9vzvp36gtklvjf0xjzgcnp/

**Comment by anthlic** [comment]
@sdalmeida thanks for reply Simon.
I have restarted the node quite a few times. When i check the status i see that the blockRecvCnt is incrementing.
How do i know when it is synced though?

**Comment by sdalmeida** [comment]
@anthlic Usually what I do is that I check whats the last block that got synced on my server
```
./jcli rest v0 node stats get --host "http://127.0.0.1:3100/api"
```

Then I get that hash and check it on the Shelley Explorer site:
https://shelleyexplorer.cardano.org/en/epochs/
