### ISSUE TITLE
successfully registered my stakepool 4 days ago but does not show up

### ISSUE THREAD

**Issue by AlwaysOn24** [cardano-foundation/incentivized-testnet-stakepool-registry#1433]
I successfully registered my stakepool with the id 056b338674117592230cda736a6d65e22cb6bee50a9c72dcb8f114bc1907063f
, but i can not see the full metadata: where is it. what went wrong?

**Comment by AlwaysOn24** [comment]
https://shelleyexplorer.cardano.org/en/stake-pool/056b338674117592230cda736a6d65e22cb6bee50a9c72dcb8f114bc1907063f/
no TICKER, HOME PAGE, NAME and PLEDGE ADDRESS is shown. only fixed cost (0.000001) and margin (7.8%) are shown.

**Comment by sdalmeida** [comment]
@AlwaysOn24 Do you have a link to your pool registration PR? Doesn't seem like your pool is actually registered.
Looking at the link you provided, the pool owner is `ed25519_pk1x3qnnv8t7dh4mkwfjgfwa6uxtvxckka6el3xqeffvuhgr3kneydq0gvvl3`, but I can't find a registry entry with that information.

**Comment by AlwaysOn24** [comment]
[image: image.png]

as you can see from the printscreen, my link with my pools in the registry
is
https://github.com/AlwaysOn24/incentivized-testnet-stakepool-registry/tree/submission/registry
.
the stake_pool.id is
ed25519_pk1x3qnnv8t7dh4mkwfjgfwa6uxtvxckka6el3xqeffvuhgr3kneydq0gvvl3. I
pushed the files
ed25519_pk1x3qnnv8t7dh4mkwfjgfwa6uxtvxckka6el3xqeffvuhgr3kneydq0gvvl3.json
and
ed25519_pk1x3qnnv8t7dh4mkwfjgfwa6uxtvxckka6el3xqeffvuhgr3kneydq0gvvl3.sig
into the registry. I may be confused a little, but
"ed25519_pk1x3qnnv8t7dh4mkwfjgfwa6uxtvxckka6el3xqeffvuhgr3kneydq0gvvl3" I
dont know about it.

**Comment by sdalmeida** [comment]
@AlwaysOn24 I dont see your pool in the registry.

I checked both your repo ([here](https://github.com/AlwaysOn24/incentivized-testnet-stakepool-registry/blob/master/registry/ed25519_pk1x3qnnv8t7dh4mkwfjgfwa6uxtvxckka6el3xqeffvuhgr3kneydq0gvvl3.json)) and cardano-foundation repo ([here](https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/blob/master/registry/ed25519_pk1x3qnnv8t7dh4mkwfjgfwa6uxtvxckka6el3xqeffvuhgr3kneydq0gvvl3.json)) and I don't see your registry.

I did however see is that you created a staking pool named RUNUP (which is owned by `ed25519_pk17600h3qdrvv9uvxfmr2txv64e2tfxmxps9ylg9caqk8g7gjspmlqstaz0c`. This address is different than the one you provided in your first post).

If `RUNUP` the staking pool you are trying to run, check to see if you can find the private key associated to `ed25519_pk17600h3qdrvv9uvxfmr2txv64e2tfxmxps9ylg9caqk8g7gjspmlqstaz0c`

**Comment by AlwaysOn24** [comment]
sorry, i mixed it up completely. where to begin to make it again from
scratch? what i dont understand is after having created a stake pool: how
is the stake pool connected with the "owner.pub, prv , addr and the
json/sig" complex?

**Comment by sdalmeida** [comment]
When you register your pool in github, you specified the wallet public key + wallet address in that `.json` file. With the wallet private key, you signed that `.json` file and the output is the `.sig` file. 

You can follow the video tutorial here if you're having issues creating a stakepool:
https://www.youtube.com/watch?v=S01Qx-4RtrQ

Because you're running the incentived node, you need to fund your wallet using Daedalus (or using the `cardano-wallet` command). In either case, you needed to have had some ADA in your wallet before the snapshot took place (back in late November).

My pool costed me around 500 ADA to publish (which you can see in the in Part 4 of that video tutorial).

**Comment by KtorZ** [comment]
@AlwaysOn24 , is this ticket still relevant ?
