### ISSUE TITLE
Logs shows - OS ERROR 110

### ISSUE THREAD

**Issue by akarthikeyan16** [cardano-foundation/incentivized-testnet-stakepool-registry#1460]
Dear Team,

I am receiving lots of OS error in my node ADPL - Ubuntu - hosted in VPS.

Need help and advise to solve this error.

Thanks,
karthik

**Comment by akarthikeyan16** [comment]
![OS ERROR 110](https://user-images.githubusercontent.com/9567299/71963986-b89b5880-3237-11ea-88dd-ffab19a8b3f0.PNG)
![OS ERROR 110_handshake error](https://user-images.githubusercontent.com/9567299/71963992-bcc77600-3237-11ea-9f69-e3c1702c5850.PNG)
uploaded error screenshots

**Comment by akarthikeyan16** [comment]
is this a known issue ?

**Comment by KtorZ** [comment]
Hi @akarthikeyan16 , for any issues regard `jormungandr` or `jcli`, I suggest you have a look at their official repository https://github.com/input-output-hk/jormungandr/issues. 

Make sure to look in existing tickets before opening a new one :+1:
