### ISSUE TITLE
Registering a new pool with same owner: Daedalus duplicates but Yoroi does nothing

### ISSUE THREAD

**Issue by RajaMBZ** [cardano-foundation/incentivized-testnet-stakepool-registry#1504]
It has been talked earlier in #727 that Daedalus doesn't remove the old registration done with the owner key and displays the search like this:

![daedalus](https://user-images.githubusercontent.com/34947728/72164146-f8ed0900-33e6-11ea-8271-6eeb9c2f8088.PNG)

This is not a big issue as the older one eventually starves and goes down the list, while the currently online one goes up. However, the real issue lies in Yoroi wallet:

![yoroi](https://user-images.githubusercontent.com/34947728/72164405-74e75100-33e7-11ea-9f76-d2fce84d148e.PNG)

It is ONLY displaying the older one, and not updating to the newer registration.

**Comment by KtorZ** [comment]
Hi @RajaMBZ ! This is a known issue with Yoroi's backend that they're actively working on. Hoping this will resolve soon!
