### ISSUE TITLE
Daedalus ITN not showing my ticket pool

### ISSUE THREAD

**Issue by atfpool** [cardano-foundation/incentivized-testnet-stakepool-registry#1587]
Hello,

The pool is registered in the blockchain and can be see in the shelley explorer searching by id (f9ae8a75c3256beeed42285a0be0351ef2b8cedd2f916f2aef71b9219892a8ae). 

Follow this, i done the pull request for make my pool/ticket visible in Daedalus Rewards (pr #1261 - https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/pull/1261/commits/ef7b59f876af27b9c827e577fb408a9ed2407f33).

 The problem is that the pr seems ok and merged, but the pool/ticket is not showing in Daedalus Rewards.

Any idea? Thanks!!!

**Comment by KtorZ** [comment]
Hi, the pool id you are pointing here have the following owners:

- `ed25519_pk1a70urax8wc52r58jz2ueklfnsrkxp504w92jf7v4cemzume3u2rs7exvs7`

Yet, in your metadata registration #1261 , the owner is:

- `ed25519_pk14tqyzgrm49mfq57r7sv7vrjfx0gful8r49psnm8rn0f5yk4gyqwqy0092n`

As far as I can see, there;'s no metadata attached to the first owner. Hence why it is not showing up in the repository. The following issue may help you moving forward: https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/issues/641
