### ISSUE TITLE
Slow block update, node is not catching up

### ISSUE THREAD

**Issue by slackwaree** [cardano-foundation/incentivized-testnet-stakepool-registry#1599]
I have noticed that my jormungandr is way in the past, according to ADApools we are at height #100701 and my node is still in Epoch 14.
What is even more annoying that it synches a bit after starting up then it goes into a stuck state forever, I can check the lastBlockHeight in 1 hour 2 hours or 2 days its the same until I restart the node then it does the same thing it synches a bit then gets stuck.

Any solution for this? Version is included in the log.
---
blockRecvCnt: 800
lastBlockContentSize: 315
lastBlockDate: "14.11433"
lastBlockFees: 800000
lastBlockHash: 0c79a8f9991be7d2bc4014dd166a58291feb79cefe923992450d7862e8ceb410
lastBlockHeight: "47162"
lastBlockSum: 108092083382
lastBlockTime: "2019-12-28T01:34:43+00:00"
lastBlockTx: 1
lastReceivedBlockTime: "2020-01-15T12:55:22+00:00"
state: Running
txRecvCnt: 60
uptime: 12437
version: jormungandr 0.8.5-3db0680

**Comment by KtorZ** [comment]
Hi @slackwaree , sorry to hear that. Yet, for any issue with `jormungandr` or `jcli`, please refer to their official repository: https://github.com/input-output-hk/jormungandr/issues. 

Make sure to look for existing issues before opening a new one!
