### ISSUE TITLE
My ticker doesn't appear in Daedalus and Yoroi

### ISSUE THREAD

**Issue by jproes** [cardano-foundation/incentivized-testnet-stakepool-registry#1625]
Hello,
my nodo was aproved two days ago, but doesn't appear in Daedalus and Yoroi.
I read other issues, but I can't find the answer.
My public_key is: ed25519_pk177gu57qc0v96jwgetvnevkxvfk8ufx4p0dddcav4a2fy5ln9u6vsw254sn
My ticker "JPROE".
I have to do something or only wait?
Thanks for your response.

**Comment by KtorZ** [comment]
Have you also registered your pool on-chain using a registration certificate?

**Comment by jproes** [comment]
I think so. 
I have followed all the videos and in 6 the registration is done. I don't know what I can miss

**Comment by KtorZ** [comment]
What is your stake pool id?

**Comment by jproes** [comment]
dc84db79cc3bbbfa12ccedafc42338eeedc242755d3f1b76a7943c6a26d74503

**Comment by KtorZ** [comment]
Hmmm. Your pool doesn't exist on the incentivized testnet network. 
Are you sure to have registered your pool to the right network (i.e. ITN and not another nightly network?)

**Comment by jproes** [comment]
I dont know. I have followed the 7 installation videos and everything went well. If something else needs to be done I have not found it. 
I think I'm going to turn off the computer while it resolves. The server apparently works fine.

**Comment by KtorZ** [comment]
What genesis block hash do you use?

**Comment by jproes** [comment]
nightly 9409af111b04896c756c1cee3b7f9bae8b9ed1843c9e0a5f07d92ab9b62f6f78

**Comment by KtorZ** [comment]
Then you have your answer :) 
Daedalus does not connect (by default) to nightly but it connects to the incentivized testnet (`8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676`). Your pool is on another network, hence why it doesn't show up.

**Comment by jproes** [comment]
What do i do then? Do I have to redo everything? And what genesis block did I take then? Thank you

**Comment by KtorZ** [comment]
You gotta redo pretty much everything you did but, using the current incentivized testnet network instead. You can find details (configuration parameters and genesis hash) here: https://hydra.iohk.io/build/1579767/download/1/index.html

What you're looking for is what corresponds to "itn_rewards_v1"
