### ISSUE TITLE
Signature Validation failed

### ISSUE THREAD

**Issue by darrenjschumaker** [cardano-foundation/incentivized-testnet-stakepool-registry#165]
have tried submitting pull requests multiple times and keep getting signature validation failed

execute the following in powershell

cls
Set-Location E:\Testnet\jormungandr

.\jcli.exe key generate --type ed25519 | tee owner.prv | .\jcli.exe key to-public > owner.pub

.\jcli.exe address account --testing --prefix addr $(cat owner.pub) > owner.addr

create the .json file as
{
  "owner": "ed25519_pk1yeyj2jwskjkcd3h8zllj33mglskgg5qkq0mdq4khnclc8xywap3qyen8kf",
  "name": "ChampADA Stake Pool",
  "ticker": "CHAMP",
  "homepage": "https://champada.io",
  "pledge_address": "addr1s5nyjf2f6z62mpkxuutl72x8dr7zepzszcpld5zk670rlquc3m5xysvm4zc"
}

.\jcli.exe key sign --secret-key .\owner.prv --output "ed25519_pk1yeyj2jwskjkcd3h8zllj33mglskgg5qkq0mdq4khnclc8xywap3qyen8kf.sig" .\ed25519_pk1yeyj2jwskjkcd3h8zllj33mglskgg5qkq0mdq4khnclc8xywap3qyen8kf.json

**Comment by darrenjschumaker** [comment]
See https://buildkite.com/input-output-hk/production-stakepool-registry/builds/322#bdef704b-8e42-44c9-99c5-db1f325c4144 as an example.  I've closed the previous pull requests that failed.

**Comment by KtorZ** [comment]
Your last PR seems fine --> https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/pull/161

Did you find what cause causing an issue?

**Comment by darrenjschumaker** [comment]
Not exactly.  My last submission, which currently shows as OK, initially failed the automated checks with the msg signature validation failed.  I checked it an hour or so after it failed and it had changed from failed to passed.  Not sure if someone manually reviewed and passed it or a subsequent process passed it.

________________________________

**Comment by KtorZ** [comment]
There's no ad-hoc validation process for signatures no, so I suppose it was simply still building in the background and got updated later. Thanks for the info.

**Comment by darrenjschumaker** [comment]
I have a question i hope you can answer or point me in the right direction for one.  If I need to change the pledge address being used for my stake pool in the github commit - what would the process be?  Delete the existing files, commit and pull then create new json/sig files and commit/pull?


________________________________

**Comment by KtorZ** [comment]
Hey @darrenjschumaker :) 
The process would be to simply: 

- Update your JSON file to carry your new address 
- Sign this new file to authenticate the changes (and therefore, replace the old signature)
- Commit the changes and make a PR

**Comment by darrenjschumaker** [comment]
Thanks for the prompt follow up Matthias.

And if I was updating the owner key as well --  Wouldn't the file name need to be different since the public key would be different as well?  How would that affect the process?

________________________________

**Comment by KtorZ** [comment]
There's no defined process for removing something from the registry _unfortunately_. We should probably mention that in the README :grimacing:. We _could_ but let's see this as an exercise for the upcoming MainNet blockchain ^.^ ... once submitted to the chain, your registration is there forever. Yet, if you _really_ need to remove something from a registry, then opening an issue to ask for it is a possibility. 

To be more specific about your concern, a different owner public key means indeed a different metadata file. If you want to re-use the same ticker, then you would have to first update the old metadata to a dummy / placeholder ticker and submit a new metadata pair of files named after your new public key.

**Comment by darrenjschumaker** [comment]
I think I'm going to need to do this.  If my pull request hasn't been merged yet, could I close the request and just resubmit with correct keys?

________________________________

**Comment by KtorZ** [comment]
Of course! cc @admin-cf

**Comment by darrenjschumaker** [comment]
That uncomplicated things very nicely 🙂  Have a nice day!

________________________________

**Comment by darrenjschumaker** [comment]
Hi Matthias,
Could you please look at https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/pull/341

I've recreated my json and signed with my wallet private key and submitted.  I'm following the directions to the letter.

Can you point me in the right direction?

________________________________

**Comment by darrenjschumaker** [comment]
Tried a few more times just to make sure - still failing, but the latest is:

https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/pull/346

signature verification failed

I closed the previous pull requests - 346 is the latest iteration of failing the signature verification checks.

These are my powershell commands
extract my private key from wallet mnemonic
cardano-wallet.exe mnemonic reward-credentials

--private key returned (represented as $$ below for obvious reason)
Set-Location E:\Cardano-Testnet\jormungandr


$ACCOUNT_SK = "$$"
$ACCOUNT_SK | Out-File -Encoding oem .\owner.prv
$ACCOUNT_SK = cat .\owner.prv

$ACCOUNT_PK = $ACCOUNT_SK | .\jcli key to-public
$ACCOUNT_PK | Out-File -Encoding oem .\owner.pub
$ACCOUNT_PK = cat .\owner.pub

$ACCOUNT_ADDR = .\jcli address account --testing --prefix addr $ACCOUNT_PK
$ACCOUNT_ADDR | Out-File -Encoding oem .\ownerAddress.txt


JCLI to sign the json file
Set-Location E:\Cardano-Testnet\jormungandr

.\jcli.exe key sign --secret-key .\owner.prv --output ed25519_pk1dfnss5ujrnex9dgdv92lcndwqc820p9v7pffg8zl6vq8gedz8udsl3kutf.sig .\ed25519_pk1dfnss5ujrnex9dgdv92lcndwqc820p9v7pffg8zl6vq8gedz8udsl3kutf.json



I don't do this step until after the git clone
copy .\ed25519_pk1dfnss5ujrnex9dgdv92lcndwqc820p9v7pffg8zl6vq8gedz8udsl3kutf.json C:\Users\Darren\incentivized-testnet-stakepool-registry\registry
copy .\ed25519_pk1dfnss5ujrnex9dgdv92lcndwqc820p9v7pffg8zl6vq8gedz8udsl3kutf.sig C:\Users\Darren\incentivized-testnet-stakepool-registry\registry




These are all my steps from git bash

Darren@DESKTOP-IEIBD99 MINGW64 ~
$ git clone git@github.com:darrenjschumaker/incentivized-testnet-stakepool-registry.git
Cloning into 'incentivized-testnet-stakepool-registry'...
remote: Enumerating objects: 61, done.
remote: Counting objects: 100% (61/61), done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 1375 (delta 28), reused 29 (delta 12), pack-reused 1314
Receiving objects: 100% (1375/1375), 305.35 KiB | 1.48 MiB/s, done.
Resolving deltas: 100% (589/589), done.

Darren@DESKTOP-IEIBD99 MINGW64 ~
$ cd ~/incentivized-testnet-stakepool-registry

Darren@DESKTOP-IEIBD99 MINGW64 ~/incentivized-testnet-stakepool-registry (master)
$ git checkout -b submission
Switched to a new branch 'submission'

Darren@DESKTOP-IEIBD99 MINGW64 ~/incentivized-testnet-stakepool-registry (submission)
$ cd registry

Darren@DESKTOP-IEIBD99 MINGW64 ~/incentivized-testnet-stakepool-registry/registry (submission)
$ pwd
/c/Users/Darren/incentivized-testnet-stakepool-registry/registry

Darren@DESKTOP-IEIBD99 MINGW64 ~/incentivized-testnet-stakepool-registry/registry (submission)
$ git remote -v
origin  git@github.com:darrenjschumaker/incentivized-testnet-stakepool-registry.git (fetch)
origin  git@github.com:darrenjschumaker/incentivized-testnet-stakepool-registry.git (push)

Darren@DESKTOP-IEIBD99 MINGW64 ~/incentivized-testnet-stakepool-registry/registry (submission)
$ git remote add submission git@github.com:darrenjschumaker/incentivized-testnet-stakepool-registry

Darren@DESKTOP-IEIBD99 MINGW64 ~/incentivized-testnet-stakepool-registry/registry (submission)
$ cd ..

Darren@DESKTOP-IEIBD99 MINGW64 ~/incentivized-testnet-stakepool-registry (submission)
$ git add .

Darren@DESKTOP-IEIBD99 MINGW64 ~/incentivized-testnet-stakepool-registry (submission)
$ git commit -m 'CHAMP'
[submission 8c9ecff] CHAMP
 2 files changed, 8 insertions(+)
 create mode 100644 registry/ed25519_pk1dfnss5ujrnex9dgdv92lcndwqc820p9v7pffg8zl6vq8gedz8udsl3kutf.json
 create mode 100644 registry/ed25519_pk1dfnss5ujrnex9dgdv92lcndwqc820p9v7pffg8zl6vq8gedz8udsl3kutf.sig

Darren@DESKTOP-IEIBD99 MINGW64 ~/incentivized-testnet-stakepool-registry (submission)
$ git push
fatal: The current branch submission has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin submission


Darren@DESKTOP-IEIBD99 MINGW64 ~/incentivized-testnet-stakepool-registry (submission)
$ git push submission HEAD
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 4 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 760 bytes | 190.00 KiB/s, done.
Total 5 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote:
remote: Create a pull request for 'submission' on GitHub by visiting:
remote:      https://github.com/darrenjschumaker/incentivized-testnet-stakepool-registry/pull/new/submission
remote:
To github.com:darrenjschumaker/incentivized-testnet-stakepool-registry
 * [new branch]      HEAD -> submission

Darren@DESKTOP-IEIBD99 MINGW64 ~/incentivized-testnet-stakepool-registry (submission)












________________________________

**Comment by darrenjschumaker** [comment]
Finally got it to go through, I think.  See https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/pull/348

I just forked the project and uploaded my json/sig files through the web browser into github and merged to my master branch and then did a pull request.  Went right through.  Same files I was submitting through the command line that were failing signature checks.  No idea what the problem was/is.



________________________________

**Comment by KtorZ** [comment]
Windows and UTF-8 encoding seems not to play nicely together. You're not the first one reporting issues regarding this. Glad to see you've found a way.
