### ISSUE TITLE
Question: I have two pools same ticker, can i change the title & description on each?

### ISSUE THREAD

**Issue by cheapstaking** [cardano-foundation/incentivized-testnet-stakepool-registry#1800]
In an attempt to create an additional pool using the create pool script, I used the same private key from my first pools wallet address.

This has create two pools with the same ticker, with the same meta data as per the wiki here https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/wiki 

I want to run both pool IDs I just want to differentiate between - is it possible to change the description and title of both pools some how in a pull request? If so can details be provided on how to achieve this or what I must do.

This is how it appears today:
![2](https://user-images.githubusercontent.com/58901769/73509597-851da980-4444-11ea-87fc-14fda856d3a2.png)

Want to change it as below:
![1](https://user-images.githubusercontent.com/58901769/73509607-8d75e480-4444-11ea-8d23-53f79a60d37f.png)

**Comment by KtorZ** [comment]
Hey! You'll have to change the owner account associated with one of the pool. Metadata are per owner, and not per pool. Have a look at https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/issues/641 for more details.
