### ISSUE TITLE
The ticker EVER has 2 pools

### ISSUE THREAD

**Issue by keynobase** [cardano-foundation/incentivized-testnet-stakepool-registry#1844]
Hi,

I've has 2 pools associated to the same wallet, and also over the same ticker. One pool is running, and the second is stoped. Can you delete the stopped pool ?

The pool id's are : 

GOOD , running, -> d7ad46b7628f6d6f86a3a439d3e5e3097e79e753cbce06061f28c3346f29648e
BAD, stopped -> 47902d91eddfb1794ed075d1a54d764f6b2f70800bc3d83f7608388a110a6f10

Regards,

**Comment by KtorZ** [comment]
Have a look at https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/issues/768
Cheers.

**Comment by keynobase** [comment]
The problem is that the second pool is the good pool,ranking 700, and has
best parameters than the bad ,ranking 400.

I don't know how put the good before the bad.
