### ISSUE TITLE
cardano-wallet CLI doesnt have an option for mnemonic command called "reward-credentials"

### ISSUE THREAD

**Issue by cpekiner** [cardano-foundation/incentivized-testnet-stakepool-registry#195]
In the instructions to obtain private key of the current wallet, the readme mentions to use 
cardano-wallet mnemonic reward-credentials option which doesn't exists. It only have "generate" command option. How can we get our private key out?

**Comment by Vetro7** [comment]
https://github.com/input-output-hk/cardano-wallet/commit/f1680bf08cbe18a848160b6d80b98ef8e96de288

It was added a few days back, you can either build from current source or wait for the new binary release

**Comment by KtorZ** [comment]
We are working on providing pre-built binaries in a proper release A.S.A.P.

**Comment by KtorZ** [comment]
See: https://github.com/input-output-hk/cardano-wallet/releases/tag/v2019-12-09
