### ISSUE TITLE
VOIDED pools still visible in wallets

### ISSUE THREAD

**Issue by Scitz0** [cardano-foundation/incentivized-testnet-stakepool-registry#2073]
Voided pools with PR https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/pull/2005
Merged 7 days ago to master but pools are still listed in Daedalus/Yoroi with ticker VOID7 and searchable with pool name as only ticker was updated in void PR. 
Have I missed some step in VOID process or do I have to create a new PR to remove the rest of the data(pool name and website) to not make it visible on search?

**Comment by KtorZ** [comment]
Please refer to: https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/issues/768. 

Cheers.
