### ISSUE TITLE
Help for Running Stake Pool Operators

### ISSUE THREAD

**Issue by mahdialaa** [cardano-foundation/incentivized-testnet-stakepool-registry#2127]
Dear Mr/Ms,

It's Mahdi from Iran,
I would like to launch a stack pool in Iran and Please help me with the following items.

1.Minimum server hardware specifications (CPU, RAM, HDD, ...)
2.Server OS (Windows Server 2019 Data Center with GUI is ok?)
3.Minimum clients hardware specifications (CPU, RAM, HDD, ...)
4.Is a firewall needed? if Yes, Please recommend models.
5.Is it possible to have multiple Public IP4, for coverage if interrupted internet connection?
6.Minimum bandwidth for internet connection.

Best Regards

**Comment by KtorZ** [comment]
Hi. This repository is only about the stake pool registry. For any help with setting up a stake pool on the ITN, I suggest you reach out directly to [jormungandr](https://github.com/input-output-hk/jormungandr)
