### ISSUE TITLE
Missing instructions for migrating byron wallet

### ISSUE THREAD

**Issue by Myriada** [cardano-foundation/incentivized-testnet-stakepool-registry#223]
Hi,

i am following the [registration instructions](https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/wiki/How-to-Register-Your-Stake-Pool) - in the prerequisites there is a mention of migrated wallets. 

    Have your Daedalus wallet 15-word mnemonic ready. Only migrated wallets can be used in the steps described below. Old Byron wallets need to be migrated first.

My test wallet on Daedalus passed all balance checks pre and after snapshot, but i don't have a 15 word mnemonic, only a 12 word one. 
If there are steps to migrate wallets on the testnet, manually, i could not find them (i suppose using cardano-wallet migrate would be an option?) 

It would be helpful to have an authoritative answer on how to do the migration, since it blocks pool registration for anyone with an older wallet.

If pointed to a correct doc, i can prepare the PR :)

**Comment by KtorZ** [comment]
Please, have a look at: https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/wiki/How-to-migrate-a-Byron-wallet-using-the-command-line

**Comment by edescourtis** [comment]
Just out of curiosity what is the `GENESIS_HASH`?

**Comment by edescourtis** [comment]
https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/wiki/Protocol-Parameters-%28nightly%29

**Comment by KtorZ** [comment]
Added a link earlier in the guide to make it clearer:

![Screenshot from 2019-12-10 11-23-40](https://user-images.githubusercontent.com/5680256/70521462-941c6580-1b3f-11ea-8f7f-add6c8275827.png)
