### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by A-Caccese** [cardano-foundation/incentivized-testnet-stakepool-registry#239]
Following suggestions on official workgroup I tried to insert a newline into the json file. Than I update the signature, but it's still not work. I'm not figuring out what missing...

jcli 0.8.0-rc10 on Ubuntu 18.04

**Comment by A-Caccese** [comment]
Pull request CSP.

**Comment by KtorZ** [comment]
Hi @A-Caccese , it seems that your PR (https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/pull/238) is currently _"empty"_. Would you be able to rebase it to a state where there's only a single commit adding the JSON file and the corresponding signature?

**Comment by A-Caccese** [comment]
Hi KtorZ, I resolved pushing directly the files to my repo from command line. Copy-paste isn't a smart solution for formatted files. :) Thanks.
