### ISSUE TITLE
Get the owner key

### ISSUE THREAD

**Issue by wstrik** [cardano-foundation/incentivized-testnet-stakepool-registry#28]
The manual sas:
>  ⚠️ If you want to be able to monitor your rewards inside Daedalus or Yoroi, make sure to derive your owner public key from your mnemonic sentence at the right derivation path (e.g `m/1852'/1815'/0'/2/0`).

But how would someone do that?

**Comment by KtorZ** [comment]
Indeed. This is now available as a command of `cardano-wallet`. The steps are explained in [
Option A: deriving your key from your mnemonic](https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/wiki/How-to-Register-Your-Stake-Pool#step-2-get-your-reward-credentials)
