### ISSUE TITLE
How do I make the pull request?

### ISSUE THREAD

**Issue by adatown** [cardano-foundation/incentivized-testnet-stakepool-registry#284]
change is here https://github.com/adatown/incentivized-testnet-stakepool-registry

**Comment by bjarnekvae** [comment]
https://gist.github.com/Chris-Graffagnino/92c1ccc79eb4c63fec39b2d80dd4d1ad

Remember to buy him a beer :)

**Comment by Rugbertl** [comment]
1. Go to tab "Pull requests"
2. Click the button "New pull request"
3. Click on compare across forks
4. Select your fork at the right dropdown
5. Commit

**Comment by adatown** [comment]
My fork isn't in the right dropdown

**Comment by adatown** [comment]
Thanks Chris Graffagnino, I missed a step - your guide helped me find that.
