### ISSUE TITLE
Get the "pledge_address"

### ISSUE THREAD

**Issue by wstrik** [cardano-foundation/incentivized-testnet-stakepool-registry#29]
Can't find a way to get the pledge_address;
The manual says:
> ❓ The pledge_address can be any valid address you own. However, we recommend using the account address corresponding to your Daedalus or Yoroi assigned reward account. This account may also be used to fund your registration certificate for your stake pool.

But my address in Daedalus has uppercase characters in it.

**Comment by StakerSpace** [comment]
Yes, we would also like to know what this exactly means. So the pledge address is one of the addresses that we used for the snapshot. How do we derive the addresses and is it possible to do this offline ?

**Comment by edescourtis** [comment]
Any update on this?

**Comment by SViksha** [comment]
use on where jcli is installed if you already have your private and public key 

./jcli address account --testing --prefix addr **YOUR PUBLIC KEY** > owner.addr

owner.addr file will have generated address

**Comment by KtorZ** [comment]
@wstrik @edescourtis 

You'll have to:

1/ Migrate your Byron wallet to a new Shelley wallet (see https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/wiki/How-to-migrate-a-Byron-wallet-using-the-command-line)

2/ Get your reward credentials as described in Step 2: https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/wiki/How-to-Register-Your-Stake-Pool#step-2-get-your-reward-credentials

**Comment by wstrik** [comment]
Hi @KtorZ,

Just did the migration. Here are the PowerShell scripts:

[Step 2: Restore Your Byron Wallet](https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/wiki/How-to-migrate-a-Byron-wallet-using-the-command-line#step-2-restore-your-byron-wallet)
`$response = curl http://localhost:8090/v2/byron-wallets `
`-Method POST `
`-Headers @{"Content-Type"="application/json"} `
`-Body '{'
    "name": "MyByronWallet",
    "passphrase": "MySecurePassphrase",
    "mnemonic_sentence": [
      "survey",
      "wonder",
      ...
  ]}' `
`echo $response.Content`

`$BYRON_ID='aa129a07d1ce083e67597348f1788747a034686e'`

[Step 4: Migrate your Byron wallet](https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/wiki/How-to-migrate-a-Byron-wallet-using-the-command-line#step-4-migrate-your-byron-wallet)
`curl http://localhost:8090/v2/byron-wallets/$BYRON_ID/migrations/$SHELLEY_ID `
`  -Method POST `
`  -Headers @{"Content-Type"="application/json"}`
`  -Body '{
    "passphrase": "MySecurePassphrase"
  }'`
