### ISSUE TITLE
I/O error: stream did not contain valid UTF-8

### ISSUE THREAD

**Issue by wstrik** [cardano-foundation/incentivized-testnet-stakepool-registry#30]
When running step 4 "Sign it using your owner private key". I got the following error.
`I/O error
  |-> stream did not contain valid UTF-8`

Guess it has something to do with the json file. But my text editor confirmed it was UTF-8. Also tried UTF-8-BOM and changing the EOL between Windows en Linux. All without luck.
Here's my json file:
`{
    "owner": "ed25519_pk1usgfv24ty27qzs755zqtjkfcuh8m7hxkzmh64tl3s6ge2pk9yg8qf0zv7j",
    "name": "ADA Straking Zone",
    "ticker": "ASZ",
    "homepage": "https://strikingsoftware.nl/ada/",
    "pledge_address": "addr1qhjpp9324v3tcq2r6jsgpw2e8rjul06u6ctwl2407xrfr9gxc53qulr4kt0"
}`

Also doing this from a Windows machine.

**Comment by matthaus000** [comment]
I have the same problem and no luck here either :(

**Comment by KtorZ** [comment]
@wstrik @matthaus000 I assume you are running on Linux or Mac OS. what does the `locale` command returns you?

In my case: 
```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=fr_FR.UTF-8
LC_TIME=fr_FR.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=fr_FR.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=fr_FR.UTF-8
LC_NAME=fr_FR.UTF-8
LC_ADDRESS=fr_FR.UTF-8
LC_TELEPHONE=fr_FR.UTF-8
LC_MEASUREMENT=fr_FR.UTF-8
LC_IDENTIFICATION=fr_FR.UTF-8
LC_ALL=
```

You could try re-running the command by forcing the `LC_ALL` environment variable to `en_US.UTF-8` (`LC_ALL=en_US.UTF-8 jcli key sign ...`). That's a wild guess, but _maybe_.

**Comment by wstrik** [comment]
Hi @KtorZ, thx for your reply. I can't speak for @matthaus000, but I'm running on Windows. Also my locale er set to en US.

**Comment by KtorZ** [comment]
Any help maybe for you here: https://github.com/input-output-hk/jormungandr/issues/503 ?

**Comment by matthaus000** [comment]
Yes I am on Windows 10 also. Someone told me to do this in Notepad++ besides also setting it to UTF-8 in there (see attached image).
![photo_2019-12-10_01-01-34](https://user-images.githubusercontent.com/58592636/70525436-43d0f200-1b97-11ea-83bc-a31a78167a73.jpg)

**Comment by matthaus000** [comment]
Ok the reason its not working because in Notepad++ you are chaning the encoding of the .json file to UTF8 only I  guess. You have to also change the encoding of the owner file to UTF8 as well and then it should work.

**Comment by matthaus000** [comment]
Let me know if that works for you as that is what worked for me. cheers....

**Comment by KtorZ** [comment]
:thinking: We could probably fix this in the CI validator too though. Good findings :pray:

**Comment by matthaus000** [comment]
Here to help one another... that is what it is all about. cheers all

**Comment by KtorZ** [comment]
I'll mark this as closed, with the following notes:

- Make sure all files (.json, .sig and the owner.prv) are UTF-8 encoded
- Make sure files use UNIX newlines (`\n`) instead of Windows newlines (`\r\n`)
