### ISSUE TITLE
The CI is failing even though the checks are passed fine.

### ISSUE THREAD

**Issue by valuepool** [cardano-foundation/incentivized-testnet-stakepool-registry#403]
Seems to be happening for all pull request since 2019-12-13 00:00 CET.

**Comment by KtorZ** [comment]
Hey! Indeed, we allocated some more machines yesterday to the integration environment and something went wrong in the process apparently. We are investigating the issue since this morning but hasn't resolved it yet.

**Comment by Vetro7** [comment]
Yes saw this just after I posted.. and was just about to back the heck off and delete that last one... I know you guys are busy..

**Comment by KtorZ** [comment]
Worry not, we are also here to help and many things are happening so, it's good that we got people to look after things for us too.

**Comment by CardanoUmbrella** [comment]
Is this related to my application failing? Or is that a separate issue?

**Comment by KtorZ** [comment]
Your application is good. Problem is on our side :upside_down_face:

Please be patient and turn on notifications on this issues if you want to be notified when the problem is resolved :pray:,

**Comment by CardanoUmbrella** [comment]
Ah that's good to know, I was starting to think I'd lost my computer chops and couldn't work out what I was doing wrong! Hope you can get it sorted without too much stress ;)

**Comment by KtorZ** [comment]
Fixed :gift_heart:
