### ISSUE TITLE
Step Two: "passphrase is too short"

### ISSUE THREAD

**Issue by CardanoUmbrella** [cardano-foundation/incentivized-testnet-stakepool-registry#436]
Hi,
I'm on step two of migrating a byron wallet to shelley wallet.
I didn't use a passphrase when I created it. When I run the command using the following
`    "passphrase": "",`

I get this error:

`{"code":"bad_request","message":"Error in $.passphrase: passphrase is too short: expected at least 10 characters"}`

If i try removing the parameter completely, I get this error. Feels like a catch-22
`{"code":"bad_request","message":"Error in $: key 'passphrase' not present"}`

How do you migrate a byron wallet that wasn't created with a passphrase?

**Comment by KtorZ** [comment]
Hi!
Your wallet passphrase is not an intrinsic element of your wallet. Said differently, it is only use by the software which restore your wallet to encrypt the root private key corresponding to your mnemonic. This doesn't however affect your mnemonic itself; restoring the same wallet using a different passphrase would work all-the-same. 

Here, you may pick any valid passphrase that will apply only to the wallet instance to which you give it. So long as your mnemonic is identical, your wallet will be restored.

**Comment by KtorZ** [comment]
(added some extra disclaimer to https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/wiki/How-to-migrate-a-Byron-wallet-using-the-command-line#step-2-restore-your-byron-wallet)

**Comment by CardanoUmbrella** [comment]
Thank you for your comprehensive and swift answer!
