### ISSUE TITLE
Stakepool registration on Pending for long time (30+ mins)

### ISSUE THREAD

**Issue by chbfiv** [cardano-foundation/incentivized-testnet-stakepool-registry#558]
stakepool_id: b6392fcd8279cf56d774cf130c801ba526256322fa62a2f642036d82a42042fc
account_address: ca1skehj4q3acs6x0a4zyu6qf4uyq22yccueqcggz947pc539jhfrv4j72azjv

```- fragment_id: 9d9b663ddda6127c177a01aa83a2077b62a99e87fc3e1fa9320e8cdb0d32b9d6 last_updated_at: "2019-12-15T08:44:28.271794080+00:00" received_at: "2019-12-15T08:44:28.271794007+00:00" received_from: Rest status: Pending```

tx_id: 31a29906a7bc0b4182ed4ba0c59ff349a40bcb15f3f2cadba92a128fadf893b6

This is blocking my stakepool registration. Because if I create a new stakepool registration it'll us ehe same fragment_id and transaction_id I think it's just seeing the message on the bus already and ignoring a re-register. Not sure what todo atm

here is the account
https://shelleyexplorer.cardano.org/en/address/ca1skehj4q3acs6x0a4zyu6qf4uyq22yccueqcggz947pc539jhfrv4j72azjv/

**Comment by chbfiv** [comment]
Also, Looks like a handful of others are facing the same thing (though maybe for different reasons)
@VaclavNavratil
```
jcli rest v0 message logs --host http://127.0.0.1:3101/api | grep -A 4 0f139eb8dc843da108e791c3c05e049efe0694bc2b115acce3cfa15b2d78efc0
- fragment_id: 0f139eb8dc843da108e791c3c05e049efe0694bc2b115acce3cfa15b2d78efc0
  last_updated_at: "2019-12-14T22:43:17.508842997+00:00"
  received_at: "2019-12-14T22:43:17.508842949+00:00"
  received_from: Rest
  status: Pending
```

@DeGuard
```
fragment_id: 963b317e6a4d9fed6fe51cf71ea63c8c33872f287952b73e7730c8a77ed0fbb6
  last_updated_at: "2019-12-14T19:09:22.287008964+00:00"
  received_at: "2019-12-14T19:09:22.287008932+00:00"
  received_from: Rest
  status: Pending
```

Dušan Mrozek
```
37a5bc19010b252e99d86f430eb86c350e6790aa07514ef2aba5988e61522d50
  last_updated_at: "2019-12-14T14:24:41.740623700+00:00"
  received_at: "2019-12-14T14:24:41.740623700+00:00"
  received_from: Rest
  status: Pending
```
@gnossienli
```
- fragment_id: 819696b5c0be655e44afb7065fdb2fb9c8c763948636ffe056b6e6520298d0d4
  last_updated_at: "2019-12-14T09:43:57.406299261+00:00"
  received_at: "2019-12-14T09:43:57.406299068+00:00"
  received_from: Network
  status: Pending
```

**Comment by chbfiv** [comment]
Also, It seems the fragment went away after an hour or so (not sure how long). So I just re-sent the stakepool cert and appears to have the same issue.

 ```
msg_logs | grep -A 7 9d9b663ddda6127c177a01aa83a2077b62a99e87fc3e1fa9320e8cdb0d32b9d6
- fragment_id: 9d9b663ddda6127c177a01aa83a2077b62a99e87fc3e1fa9320e8cdb0d32b9d6
  last_updated_at: "2019-12-15T09:58:56.621976819+00:00"
  received_at: "2019-12-15T09:58:56.621976754+00:00"
  received_from: Rest
  status: Pending
```

**Comment by KtorZ** [comment]
Hey, if a transaction is pending for too long, you may try to re-submit it. Since you're using an account, only one transaction will go through anyway (because of the account counter and the associated witnesses).

**Comment by chbfiv** [comment]
yeah that was my second commit. Still the same result

**Comment by chbfiv** [comment]
I resolved it by finding the changes made to the https://github.com/input-output-hk/jormungandr-qa scripts

(removed TAX_LIMIT) and how the cert fee isn't needed if you pay the more specific certificate_pool_registration

https://github.com/input-output-hk/jormungandr-qa/commit/3b98196ab2e61ffb55be64d14e832e32de5f19cb

**Comment by stakeada** [comment]
This doesn't work, the same issue occurs even with the commit !
