### ISSUE TITLE
Pool id is not listed when I check with jcli

### ISSUE THREAD

**Issue by plessmann** [cardano-foundation/incentivized-testnet-stakepool-registry#597]
I did all steps discribed at the most recent docs https://iohk.zendesk.com/hc/en-us/articles/900000038626, but the verification for my pool id at step 4.4 (4.4 Check that the stake pool is in the blockchain.) seems to fail

```
$ cat createStakePool_output.txt

[...]
 ##11. Remove the temporary files
  ##Waiting for new block to be created (timeout = 200 blocks = 400s)
New block was created - 0c4b6e16ce44c4d6cdc6d78994f66052b5b6aeb5539420c810a922dcaa2fec9d
 ##5. Retrieve your stake pool id (NodeId)
a78d7c2d59805db899d3ce03e4d0673cbe2e623790e1e0637dc22f0a52bdada0
============== Stake Pool details ================
Stake Pool ID:    a78d7c2d59805db899d3ce03e4d0673cbe2e623790e1e0637dc22f0a52bdada0
Stake Pool owner: ca1s54cflndqnvljq49e70pkueqa4qua6l8ewcfj3qj5jtzvg02kukag7gq4rl
TAX_VALUE:        750000
TAX_RATIO:        1/20
TAX_LIMIT:        0
==================================================
 ##6. Create the node_secret.yaml file

```

But my pool is not listed when I check it like this:

```
$ jcli rest v0 stake-pools get -h "http://127.0.0.1:3100/api" | grep a78d7c2d59805db899d3ce03e4d0673cbe2e623790e1e0637dc22f0a52bdada0
$
```
=> NO OUTPUT => the genrated stake pool id I created in advance is missing.

Both of jormungandr and jcli is an binary version of release 0.8.0.

So whats going wrong? How can I verify that all is working now?
Thanks in advance.

**Comment by KtorZ** [comment]
Hi, are you sure that your transaction carrying your registration certificate has been accepted? What does jcli logs says about it?

```
jcli rest v0 message logs --host http://127.0.0.1:3100/api
```

**Comment by plessmann** [comment]
Hey KtorZ,

# jcli rest v0 message logs --host http://127.0.0.1:3100/api
---
- fragment_id: 3b6b57512c3b3d143195b2f3a7d6ebdbdcf59d4b87301da8eed795b9e4d06155
  last_updated_at: "2019-12-17T07:22:31.247383492+00:00"
  received_at: "2019-12-17T07:22:22.146090212+00:00"
  received_from: Network
  status:
    InABlock:
      block: 0b36dec1abb704ca8e4830abd33165d4d8cd68bf875ec45a223ca93182a6bf2c
      date: "22.3409"
- fragment_id: 43d1a4a3a92e6cc1d11f9e649ef91b2fed061a2a1a20e18956aec391857378cd
  last_updated_at: "2019-12-17T07:56:36.430905150+00:00"
  received_at: "2019-12-17T07:56:36.430905045+00:00"
  received_from: Network
  status: Pending

**Comment by KtorZ** [comment]
Does the second fragment (the one that is pending) corresponds to your stake pool registration? Looks like it is pending, so something could be wrong with your transaction. You could perhaps try to re-submit your certificate (only one transaction / certificate will eventually be accepted).

**Comment by plessmann** [comment]
Why are there 2 fragment_ids? Whats the need for 2? Can I remove or should I remove the second one first?
I remember the first transaction I did was based on a legacy documentation which failed. Might be the reason for this Pending.

**Comment by plessmann** [comment]
Hi @KtorZ 

I tried to resubmit the certificate. Now i've got a new Pool Id but again Pending records:

- fragment_id: fd44e376b6e839d7c72542e76f23173ec814175a8397bed6cef54c069dc2203a
  last_updated_at: "2019-12-17T13:55:04.182610324+00:00"
  received_at: "2019-12-17T13:55:04.182610199+00:00"
  received_from: Network
  status: Pending
- fragment_id: e5b56862389153b97a7f619f5505c5a616e27fc30ba3126e2620639d4a75e968
  last_updated_at: "2019-12-17T13:49:39.775366632+00:00"
  received_at: "2019-12-17T13:49:39.775366569+00:00"
  received_from: Rest
  status: Pending
- fragment_id: 0a683f82dbc7e543f87caf1376b74b812f0e1539d5f4339176a27761b391d282
  last_updated_at: "2019-12-17T13:52:29.360178341+00:00"
  received_at: "2019-12-17T13:52:22.974690965+00:00"
  received_from: Network
  status:
    InABlock:
      block: 054fb6a7c0e6f07e4fe73503aa54d7c9676f424c64db5f48eb8fa6d5cd9fd6dc
      date: "24.708"
- fragment_id: d6c918eb736538c5d52c92c78f5452d5a57c5cbd6e53c5434d6e106da193a18e
  last_updated_at: "2019-12-17T13:53:35.363938020+00:00"
  received_at: "2019-12-17T13:52:58.723719080+00:00"
  received_from: Network
  status:
    InABlock:
      block: bab8ab7d325b73d0a98822e8ccd859ad241acebddeb36b5bb3ac8d5d01bb59d1
      date: "24.741"

**Comment by plessmann** [comment]
I think, I try it again from the beginning with jormungandr 0.8.3 and hope it works. 
Just lets remove or close the ticket. Thanks.
