### ISSUE TITLE
Correction to SAND url

### ISSUE THREAD

**Issue by michaeljfazio** [cardano-foundation/incentivized-testnet-stakepool-registry#619]
An error in the original submission of SAND has left its actual URL unreachable.

The URL should be www.sandstone.io not www.sanstone.io

Pull request to correct has been made #578

**Comment by KtorZ** [comment]
Hey! Sorry to hear that!
Pull requests are reviewed in order from oldest to newest so, your turn will come, no worries and be patient :)
