### ISSUE TITLE
request pool has been validated/delageted epoch 1 but pool but it is not visible with the command jcli epoch 2

### ISSUE THREAD

**Issue by magmerlin** [cardano-foundation/incentivized-testnet-stakepool-registry#635]
hello 

saturday "epoch 1" , my request has been validated  https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/pull/499

i delegated ada to my pool 

  jcli rest v0 account get $ ADDR -h http://127.0.0.1:3100/api
.............................
   pools:
     - - f756c8f3e31bd56bd01c569e6a130cd9026ee69a90c329374dedf42e3ee01e12
       - 1
last_rewards:
   epoch: 0
   reward: 0
value: 1098300000

But my pool does not appear with the command jcli rest v0 stake get --host "http://127.0.0.1:3100/api" => epoch2 
But my pool is visible on https://shelleyexplorer.cardano.org/en/stake-pool/f756c8f3e31bd56bd01c569e6a130cd9026ee69a90c329374dedf42e3ee01e12/

How to know if my pool is really functional ?

**Comment by KtorZ** [comment]
Hi, there's a delay between the moment you register a pool and the moment it becomes active (cf Ouroboros Praos protocol).

In short, your pool becomes active the epoch after the epoch following your registration. So if you registered on epoch 1, delegation will start at epoch 3 for you.
