### ISSUE TITLE
Delegation not working

### ISSUE THREAD

**Issue by ayuved009** [cardano-foundation/incentivized-testnet-stakepool-registry#702]
Hello
My Stackpool is appearing twice ie ADSPL.
I have delegated ada to this SP, but it is not showing up when I check using scripts
jcli rest v0 stake-pool get $STAKE_POOL_ID --host "http://127.0.0.1:3100/api

~/jcli rest v0 account get $ACCOUNT_ADDRESS -h http://127.0.0.1:3100/api
Please look into this issue
regards
NileshDT

**Comment by KtorZ** [comment]
Hi, about your first remark, please have a look at: https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/issues/727

About your second remark, keep in mind that delegation are only effective the epoch after the epoch following your delegation. So if you delegate at epoch `e`, then your delegation becomes active at `e+2` and you start getting rewards at `e+3`.
