### ISSUE TITLE
My pool is listed three times in Daedalus

### ISSUE THREAD

**Issue by marimes** [cardano-foundation/incentivized-testnet-stakepool-registry#709]
<img width="287" alt="Bildschirmfoto 2019-12-17 um 04 22 22" src="https://user-images.githubusercontent.com/12594437/70963083-bce4b380-2087-11ea-9ab9-febff5d88dc4.png">

My pool _KNTI_ is currently listed three times in Daedalus (currently ranked 9, 224, and 255). I had initially listed is under the ticker _KTI_ and did not know how to update it after they were already merged.

Please delete the registrations under the ticker for KTI.

Please **keep** my active pool _KNTI_ has a pool id of `6f23b9a72c6123b485594cc27dfc67ac870004135ee2286b92a05b592a52307c`and the owner `ed25519_pk1tjqcnwvuwzxs84d4j45czrmjvzkpvkspfqhctnlhgtvdvk5vu2wq2tx4hp`.

**Comment by KtorZ** [comment]
Hey :) 
As far as I can see, you have registered three pools with the same owner: 

- `febfc1f6560e0b82e61b949f745b1850b97218cbf65dc32a1e2dc79ca3d57bab`
- `6f23b9a72c6123b485594cc27dfc67ac870004135ee2286b92a05b592a52307c`
- `c2776732e166e3c8d7879504f08fb760c2cc57d555a5af2dc934a9b0fc5c9946`

If you want only one pool to show up, then you need to retire your old pool by submitting a retirement certificate. As far as I know, this isn't yet supported through `jcli` so it could quite unpractical. I suggest checking for an existing ticket on their official repository or opening one if none exists about the matter: https://github.com/input-output-hk/jormungandr/issues
