### ISSUE TITLE
Remove request from stake pool list

### ISSUE THREAD

**Issue by cardanocommunitykor** [cardano-foundation/incentivized-testnet-stakepool-registry#734]
The stake pool below is always offline.

Please remove it from the stake pool list in the daedalus. (invisible)

pool ID : 47717c4823ef864eee3449a52c9d2d29c20c35e757d176634d73fa2fd4847053

**Comment by KtorZ** [comment]
Hi,
This is not how things actually works. We have no power to retire pools from the chain, only their owners can do it.

This registry only holds metadata about pool owners. Pools registration however are recorded on the blockchain and are therefore subject the same laws of immutability than the rest.

If a pools perform poorly, then it'll be ranked poorly and there's little chance stakeholders might delegate to it.

Cheers.
