### ISSUE TITLE
How to move delegated amount back to rewards wallet?

### ISSUE THREAD

**Issue by D3R4** [cardano-foundation/incentivized-testnet-stakepool-registry#791]
How to move delegated amount back to new wallet?

I have delegated ADA to my own stake pool. I want to move my ada back to my new rewards wallet (or back to balance wallet) as my stake pool is not listed in Daedalus. After this I want delegate to another pool and turn off my own. How to do it? 

Node ID:201e9f71df730e2b3a8336eaf1a202caa8c4befa3db349d9d90d4c93ae81487d
jcli jormungandr v0.8.2

Thanks

**Comment by KtorZ** [comment]
Hi, in Daedalus, you can change your delegation settings at any time (modulo transaction fees to pay).

To retire a stake pool, please read through: https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/issues/768
