### ISSUE TITLE
SAND Metadata Doesn't Show in Shelly Explorer

### ISSUE THREAD

**Issue by michaeljfazio** [cardano-foundation/incentivized-testnet-stakepool-registry#849]
I've raised this with IOHK support desk however they just refer me to the online community and this GitHub repo. Not convinced its the right place for it but here goes anyway.

SAND pool does not show its registered metadata in the Shelly Explorer:

https://shelleyexplorer.cardano.org/en/stake-pool/03a01cb9acffb3374c9a86ff39b2b5d85128c9ce3ac3fdba51ceceaca0685f98/

The pool is correctly registered. The pool is operating perfectly. The pool is producing blocks.

**Comment by KtorZ** [comment]
Hi @michaeljfazio , metadata in the explorer are updated periodically (once a day if I recall correctly). However, seems like your registration was merged 7 days ago already. 

It could be a bug in the explorer due to the duplicate pool owner on your pool. I'll raise an issue with the guys.

**Comment by michaeljfazio** [comment]
There has been a few interesting things happen as a result of my accidental owner double up. Glad to be able to help out by breaking things! 👍 It was completely unintentional... in fact not even sure how it happened!

**Comment by KtorZ** [comment]
Well, you actually did something that no one thought of and ~~broke~~ made stronger a couple of things along the way. Thanks for this :blush:

**Comment by KtorZ** [comment]
Fixed -> https://shelleyexplorer.cardano.org/en/stake-pool/03a01cb9acffb3374c9a86ff39b2b5d85128c9ce3ac3fdba51ceceaca0685f98/

**Comment by michaeljfazio** [comment]
Ledgend
