### ISSUE TITLE
Create stake pool issues

### ISSUE THREAD

**Issue by napangelo** [cardano-foundation/incentivized-testnet-stakepool-registry#917]
Hi,

Using jormungandr v0.8.3-8f276c0

I followed the instructions to create a stake pool:
https://github.com/input-output-hk/shelley-testnet/blob/master/docs/stake_pool_operator_how_to.md#create-an-account-address-using-the-script

I run last version of the script:
curl -sLOJ https://raw.githubusercontent.com/input-output-hk/jormungandr-qa/master/scripts/createStakePool.sh
curl -sLOJ https://raw.githubusercontent.com/input-output-hk/jormungandr-qa/master/scripts/send-certificate.sh

Result:

```
 ##11. Remove the temporary files
  ##Waiting for new block to be created (timeout = 200 blocks = 400s)
New block was created - 2ab06d115c84d6148f6c5a79b701597d4b05b8f3e4471f253dea7679f979cae3
 ##5. Retrieve your stake pool id (NodeId)
7e410dd40ccdf1170840029cc8e6599e0ce86886f3224d7f0c90914759f5e40b
============== Stake Pool details ================
Stake Pool ID:    7e410dd40ccdf1170840029cc8e6599e0ce86886f3224d7f0c90914759f5e40b
Stake Pool owner: [hidden]
TAX_VALUE:        10000
TAX_RATIO:        1/10
==================================================
 ##6. Create the node_secret.yaml file
```

The block has been created
https://shelleyexplorer.cardano.org/en/block/2ab06d115c84d6148f6c5a79b701597d4b05b8f3e4471f253dea7679f979cae3

The stake pool id "7e410dd40ccdf1170840029cc8e6599e0ce86886f3224d7f0c90914759f5e40b" does not exist in the list

./jcli rest v0 stake-pools get --host "http://127.0.0.1:3100/api"

OR

./jcli rest v0 stake-pool get $STAKEPOOL_ID --host "http://127.0.0.1:3100/api"
failed to make a REST request
  |-> node rejected request because of invalid parameters
  |-> http://127.0.0.1:3100/api/v0/stake_pool/7e410dd40ccdf1170840029cc8e6599e0ce86886f3224d7f0c90914759f5e40b: Client Error: 404 Not Found

how come the node-id does not appear?
Thanks

**Comment by KtorZ** [comment]
Hi, I'll suggest to open an issue on https://github.com/input-output-hk/jormungandr/issues/ for any issues with Jörmungandr or `jcli`. 

Cheers
