### ISSUE TITLE
KIWI Metadata not showing in ITN Explorer

### ISSUE THREAD

**Issue by kiwipool** [cardano-foundation/incentivized-testnet-stakepool-registry#943]
Hi, same as issue as noted by Michael from SAND.

Shows up fine in Daedalus just not the explorer. Relatively new pool, waiting on start of epoch 8 for delegated stake to show up.

https://shelleyexplorer.cardano.org/en/stake-pool/ceba999d88a991f49ccc0b2fe3fee9d139e607a30a278527cc25979bfc177339/

thanks . . .

**Comment by sdalmeida** [comment]
@kiwipool I can see your pool in the shelley explorer (from the link you provided above) and in Daedalus.

![image](https://user-images.githubusercontent.com/1103528/72034347-c31f1780-3262-11ea-8f1d-bcebcb34141a.png)

Are you still having issues?

**Comment by kiwipool** [comment]
Hi Simon

Yeah, looks like this has either been fixed or resolved itself. Issue can be closed off, thanks.

matticus

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
