### ISSUE TITLE
Automated Test Fails - QIXX

### ISSUE THREAD

**Issue by phillewis** [cardano-foundation/incentivized-testnet-stakepool-registry#987]
The automated check fails for my PR with "signature verification failed".

<img width="1107" alt="Screen Shot 2019-12-22 at 3 35 33 pm" src="https://user-images.githubusercontent.com/4168159/71318906-1b6bc080-24d2-11ea-9496-bca4945bef05.png">

I have tried recreating the signature file using JCLI, but get the same (so didn't see the point of pushing the file again).

I will need additional information regarding why the verification failed when I have followed the process described in the documentation.

**Comment by An7hrax93** [comment]
i had the same problem with windows. UTF-8 and EOL conversion to unix (LF) for the json file did the trick. maybe it´s the same issue. you can use notepad++ to fix it.

**Comment by phillewis** [comment]
Thanks, I'll give it a go.
Not sure why the format of the json file should matter though, as the sig file should sign the json regardless of what it contains

**Comment by phillewis** [comment]
Thanks @An7hrax93 that was it.

I will leave the issue open so someone from the CF can review and update their documentation

**Comment by admin-cf-2** [comment]
Thank you @phillewis and especially @An7hrax93
